---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pv-claim
  labels:
    app: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  selector:
    matchLabels:
      app: kafka
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka
        tier: backend
    spec:
      volumes:
        - name: kafka-persistent-storage
          persistentVolumeClaim:
            claimName: kafka-pv-claim

      containers:
      - image: wurstmeister/zookeeper
        name: zookeeper
        ports:
        - containerPort: 2181
          name: zookeeper

      - image: {{ .zookeeperImage }}
        name: zookeeper
        imagePullPolicy: Always
        ports:
        - containerPort: 2181
          name: zookeeper

      volumes:
        - name: kafka-persistent-storage
          persistentVolumeClaim:
            claimName: kafka-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  ports:
    - port: 9092
  selector:
    app: kafka
    tier: backend
  clusterIP: None
