---
apiVersion: v1
kind: ConfigMap
metadata:
  name: director-daemon-config
data:
  BIND_PORT: '9001'
  DB_MIGRATE: 'true'
  DB_URL: jdbc:mariadb://{{ .mysql_host }}:3306/director
  DB_USER: director
  ENV_PREFIX: {{ .env_prefix }}
  JAVA_OPTS: {{ .director_daemon_java_opts }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .kafka_host }}:9092
  KAFKA_HOST: {{ .kafka_host }}:9092
  KAFKA_TOPIC_SUFFIX: {{ .kafka_topic_suffix }}
  REPORT_METRICS: "false"
  SOTA_CORE_HOST: sota-core
  SOTA_CORE_PORT: '80'
  TUF_KEYSERVER_HOST: tuf-keyserver
  TUF_KEYSERVER_PORT: '80'
  TUF_REPOSERVER_HOST: tuf-reposerver
  TUF_REPOSERVER_PORT: '80'
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: director-daemon
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: director-daemon
    spec:
      containers:
      - image: {{ .director_daemon_docker_image }}
        name: director-daemon
        envFrom:
        - configMapRef:
            name: director-daemon-config
        - secretRef:
            name: director-daemon-secret
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9001
        args:
        - "-main"
        - com.advancedtelematic.director.daemon.DaemonBoot
        resources:
          requests:
            cpu: {{ .director_daemon_cpu }}
            memory: {{ .director_daemon_mem }}
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 30
          httpGet:
            port: 9001
            path: "/health"
      imagePullSecrets:
      - name: docker-registry-key
---
apiVersion: v1
kind: Secret
metadata:
  name: director-daemon-secret
type: Opaque
data:
  DB_PASSWORD: {{ .director_daemon_db_password | b64enc }}
