---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tuf-keyserver-daemon-config
data:
  BIND_PORT: '9001'
  DB_MIGRATE: 'true'
  DB_URL: jdbc:mariadb://{{ .mysql_host }}:3306/tuf_keyserver
  DB_USER: tuf_keyserver
  JAVA_OPTS: {{ .tuf_keyserver_java_opts }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .kafka_host }}:9092
  KAFKA_HOST: {{ .kafka_host }}:9092
  KAFKA_TOPIC_SUFFIX: {{ .kafka_topic_suffix }}
  REPORT_METRICS: "false"
  TUF_VAULT_HOST: tuf-vault
  TUF_VAULT_PORT: '80'
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tuf-keyserver-daemon
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tuf-keyserver-daemon
    spec:
      containers:
      - image: {{ .tuf_keyserver_daemon_docker_image }}
        name: tuf-keyserver-daemon
        envFrom:
        - configMapRef:
            name: tuf-keyserver-daemon-config
        - secretRef:
            name: tuf-keyserver-daemon-secret
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
        args:
        - "-main"
        - com.advancedtelematic.tuf.keyserver.daemon.KeyGenerationDaemon
        resources:
          requests:
            cpu: {{ .tuf_keyserver_daemon_cpu }}
            memory: {{ .tuf_keyserver_daemon_mem }}
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 30
          httpGet:
            port: 9001
            path: "/health"
      imagePullSecrets:
      - name: docker-registry-key
---
apiVersion: v1
kind: Secret
metadata:
  name: tuf-keyserver-daemon-secret
type: Opaque
data:
  DB_PASSWORD: {{ .tuf_keyserver_daemon_db_password | b64enc }}
  TUF_VAULT_TOKEN: {{ .tuf_keyserver_vault_token | b64enc }}
