apiVersion: v1
kind: Service
metadata:
  name: {{ template "zookeeper.fullname" . }}
  labels:
    app: {{ template "zookeeper.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 2181
      name: client
    - port: 2888
      name: peer
    - port: 3888
      name: election
  selector:
    app: {{ template "zookeeper.name" . }}
    release: {{ .Release.Name }}
