---
apiVersion: v1
kind: ConfigMap
metadata:
  name: campaigner-daemon-config
data:
  BIND_PORT: '9001'
  DB_MIGRATE: 'true'
  DB_URL: jdbc:mariadb://mysql:3306/campaigner
  DB_USER: campaigner
  DEVICE_REGISTRY_HOST: device-registry
  DEVICE_REGISTRY_PORT: '80'
  DIRECTOR_HOST: director
  DIRECTOR_PORT: '80'
  ENV_PREFIX: ce_
  JAVA_OPTS: ''
  KAFKA_BOOTSTRAP_SERVERS: kafka-0:9092
  KAFKA_HOST: kafka-0:9092
  KAFKA_TOPIC_SUFFIX: ce
  MESSAGING_MODE: kafka
  REPORT_METRICS: "false"
  SCHEDULER_BATCH_SIZE: '200'
  SCHEDULER_DELAY: 10 seconds
  SCHEDULER_POLLING_TIMEOUT: 10 seconds
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: campaigner-daemon
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: campaigner-daemon
    spec:
      containers:
      - image: {{ .campaignerImage }}
        name: campaigner-daemon
        envFrom:
        - configMapRef:
            name: campaigner-daemon-config
        - secretRef:
            name: campaigner-daemon-secret
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
          name: camp-daem0
        args:
        - "-main"
        - com.advancedtelematic.campaigner.DaemonBoot
        resources:
          requests:
            cpu: '0.1'
            memory: 512Mi
        livenessProbe:
          initialDelaySeconds: 300
          periodSeconds: 30
          httpGet:
            port: 9001
            path: "/health"
      imagePullSecrets:
      - name: atsk8sregistrykey
---
apiVersion: v1
kind: Secret
metadata:
  name: campaigner-daemon-secret
type: Opaque
data:
  DB_PASSWORD: {{ .campaignerDaemonDbPassword }}
