---
apiVersion: v1
kind: ConfigMap
data:
  BIND_HOST: 0.0.0.0
  BIND_PORT: '9001'
  CLIENT_ID: 815886dc-8232-459c-bb95-c928f4873f38
  DEVICE_REGISTRY_HOST: device-registry
  DEVICE_REGISTRY_PORT: '80'
  DIRECTOR_HOST: director
  DIRECTOR_PORT: '80'
  ENV_PREFIX: ce_
  INFLUXDB_HOST: influx.k8s
  INFLUXDB_PORT: '8086'
  INFLUXDB_URI: http://influx.k8s:8086
  KAFKA_BOOTSTRAP_SERVERS: kafka-0:9092
  KAFKA_HOST: kafka-0:9092
  KAFKA_TOPIC_SUFFIX: ce
  METRICS_DB: services
  SERVICE_TCP_PORT: '8000'
  SOTA_CORE_HOST: sota-core
  SOTA_CORE_PORT: '80'
  TREEHUB_HOST: treehub
  TREEHUB_PORT: '80'
  TUF_REPOSERVER_HOST: tuf-reposerver
  TUF_REPOSERVER_PORT: '80'
  VAULT_HOST: crypt-vault
  VAULT_PORT: '80'
metadata:
  name: device-gateway-config
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: device-gateway
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: device-gateway
    spec:
      containers:
      - image: advancedtelematic/device-gateway:0.1.56
        name: device-gateway
        envFrom:
        - configMapRef:
            name: device-gateway-config
        - secretRef:
            name: device-gateway-secret
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
          name: dev-gw0
        - containerPort: 9443
          name: dev-gw1
        args:
        resources:
          requests:
            cpu: '1'
            memory: 2048Mi
        livenessProbe:
          initialDelaySeconds: 300
          periodSeconds: 30
          httpGet:
            port: 9001
            path: "/health"
      imagePullSecrets:
      - name: atsk8sregistrykey
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: device-gateway
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: device-gateway.external.kube.atsgarage.com
    http:
      paths:
      - backend:
          serviceName: device-gateway
          servicePort: 80
---
apiVersion: v1
kind: Secret
type: Opaque
data:
  CLIENT_SECRET: ${DEVICE_GATEWAY_CLIENT_SECRET}
  JWT_SECRET_KEY: ${DEVICE_GATEWAY_JWT_SECRET_KEY}
  VAULT_TOKEN: ${DEVICE_GATEWAY_VAULT_TOKEN}
metadata:
  name: device-gateway-secret
---
apiVersion: v1
kind: Service
metadata:
  name: device-gateway
spec:
  ports:
  - port: 80
    targetPort: 9001
    protocol: TCP
    name: dev-gw0
  - port: 9443
    targetPort: 9443
    protocol: TCP
    name: dev-gw1
  selector:
    app: device-gateway
