---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  KAFKA_BROKER_ID: "0"
  KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
  KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://0.0.0.0:9092
  KAFKA_ZOOKEEPER_CONNECT: localhost:2181
  KAFKA_DELETE_TOPIC_ENABLE: "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pv-claim
  labels:
    app: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka
        tier: backend
    spec:
      containers:
      - image: {{ .kafkaImage }}
        name: kafka
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: kafka-config
        ports:
        - containerPort: 9092
          name: kafka
        volumeMounts:
        - name: kafka-persistent-storage
          mountPath: /var/lib/kafka
      - image: {{ .zookeeperImage }}
        name: zookeeper
        imagePullPolicy: Always
        ports:
        - containerPort: 2181
          name: zookeeper
      volumes:
        - name: kafka-persistent-storage
          persistentVolumeClaim:
            claimName: kafka-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
    - port: 9092
  selector:
    app: kafka
    tier: backend
  clusterIP: None
