---
apiVersion: v1
kind: ConfigMap
data:
  AUTH_PROTOCOL: none
  BIND_HOST: 0.0.0.0
  BIND_PORT: '9001'
  DB_MIGRATE: 'true'
  DB_URL: jdbc:mariadb://mysql:3306/treehub
  DB_USER: treehub
  DEVICE_REGISTRY_HOST: device-registry
  DEVICE_REGISTRY_PORT: '80'
  JAVA_OPTS: "-Xmx900m"
  KAFKA_HOST: kafka-0:9092
  KAFKA_TOPIC_SUFFIX: ce
  MESSAGING_MODE: kafka
  SOTA_CORE_HOST: sota-core
  SOTA_CORE_PORT: '80'
  TREEHUB_AWS_BUCKET_ID: ats-k8s-treehub
  TREEHUB_AWS_REGION: eu-central-1
  TREEHUB_HOSTNAME: http://example.com/api/v2/mydevice
  TREEHUB_STORAGE: s3
  KAFKA_BOOTSTRAP_SERVERS: kafka-0:9092
  INFLUXDB_HOST: influx.k8s
  INFLUXDB_PORT: '8086'
  INFLUXDB_URI: http://influx.k8s:8086
  METRICS_DB: services
metadata:
  name: treehub-config
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: treehub
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: treehub
    spec:
      containers:
      - image: advancedtelematic/treehub:0.1.8
        name: treehub
        envFrom:
        - configMapRef:
            name: treehub-config
        - secretRef:
            name: treehub-secret
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
          name: treehub0
        args:
        resources:
          requests:
            cpu: '0.6'
            memory: 1048Mi
        livenessProbe:
          initialDelaySeconds: 300
          periodSeconds: 30
          httpGet:
            port: 9001
            path: "/health"
      imagePullSecrets:
      - name: atsk8sregistrykey
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: treehub
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/proxy-body-size: 30m
spec:
  rules:
  - host: treehub.external.kube.atsgarage.com
    http:
      paths:
      - backend:
          serviceName: treehub
          servicePort: 80
---
apiVersion: v1
kind: Secret
type: Opaque
data:
  DB_PASSWORD: ${TREEHUB_DB_PASSWORD}
  JWT_SECRET: ${TREEHUB_JWT_SECRET}
metadata:
  name: treehub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: treehub
spec:
  ports:
  - port: 80
    targetPort: 9001
    protocol: TCP
    name: treehub0
  selector:
    app: treehub
