---
apiVersion: v1
kind: ConfigMap
data:
  BIND_PORT: '9001'
  DB_MIGRATE: 'true'
  DB_URL: jdbc:mariadb://mysql:3306/tuf_keyserver
  DB_USER: tuf_keyserver
  INFLUXDB_HOST: influx.k8s
  INFLUXDB_PORT: '8086'
  INFLUXDB_URI: http://influx.k8s:8086
  JAVA_OPTS: "-Xmx900m"
  KAFKA_BOOTSTRAP_SERVERS: kafka-0:9092
  KAFKA_HOST: kafka-0:9092
  KAFKA_TOPIC_SUFFIX: ce
  METRICS_DB: services
  TUF_VAULT_HOST: tuf-vault
  TUF_VAULT_PORT: '80'
metadata:
  name: tuf-keyserver-config
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tuf-keyserver
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tuf-keyserver
    spec:
      containers:
      - image: advancedtelematic/tuf-keyserver:0.2.0-31-ge596ad8
        name: tuf-keyserver
        envFrom:
        - configMapRef:
            name: tuf-keyserver-config
        - secretRef:
            name: tuf-keyserver-secret
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
          name: tuf-keyserver0
        args:
        - "-main"
        - com.advancedtelematic.tuf.keyserver.Boot
        resources:
          requests:
            cpu: '0.2'
            memory: 1048Mi
        livenessProbe:
          initialDelaySeconds: 300
          periodSeconds: 30
          httpGet:
            port: 9001
            path: "/health"
      imagePullSecrets:
      - name: atsk8sregistrykey
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tuf-keyserver
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: tuf-keyserver.external.kube.atsgarage.com
    http:
      paths:
      - backend:
          serviceName: tuf-keyserver
          servicePort: 80
---
apiVersion: v1
kind: Secret
type: Opaque
data:
  DB_PASSWORD: ${TUF_KEYSERVER_DB_PASSWORD}
  TUF_VAULT_TOKEN: ${TUF_VAULT_TOKEN}
metadata:
  name: tuf-keyserver-secret
---
apiVersion: v1
kind: Service
metadata:
  name: tuf-keyserver
spec:
  ports:
  - port: 80
    targetPort: 9001
    protocol: TCP
    name: tuf-keyserver0
  selector:
    app: tuf-keyserver
