---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sota-core-config
data:
  AUTH_PROTOCOL: none
  BIND_HOST: 0.0.0.0
  BIND_PORT: '9001'
  CORE_AWS_BUCKET_ID: ats-k8s-core
  CORE_DB_URL: jdbc:mariadb://{{ .mysql_host }}:3306/sota_core
  CORE_DB_USER: sota_core
  CORE_INTERACTION_PROTOCOL: none
  DB_MIGRATE: 'true'
  DEVICE_REGISTRY_HOST: device-registry
  DEVICE_REGISTRY_PORT: '80'
  ENV_PREFIX: {{ .env_prefix }}
  JAVA_OPTS: {{ .sota_core_java_opts }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .kafka_host }}:9092
  KAFKA_HOST: {{ .kafka_host }}:9092
  KAFKA_TOPIC_SUFFIX: {{ .kafka_topic_suffix }}
  MESSAGING_MODE: kafka
  PACKAGES_VERSION_FORMAT: ".+"
  REPORT_METRICS: "false"
  SOTA_RESOLVER_PORT: '80'
  TUF_REPOSERVER_HOST: tuf-reposerver
  TUF_REPOSERVER_PORT: '80'
  USE_TUF: 'true'
  USE_USER_PROFILE: 'false'
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sota-core
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sota-core
    spec:
      containers:
      - image: {{ .sota_core_docker_image }}
        name: sota-core
        envFrom:
        - configMapRef:
            name: sota-core-config
        - secretRef:
            name: sota-core-secret
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
        args:
        resources:
          requests:
            cpu: {{ .sota_core_cpu }}
            memory: {{ .sota_core_mem }}
        livenessProbe:
          initialDelaySeconds: 300
          periodSeconds: 30
          httpGet:
            port: 9001
            path: "/health"
      imagePullSecrets:
      - name: docker-registry-key
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sota-core
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: sota-core.{{ .ingress_dns_name }}
    http:
      paths:
      - backend:
          serviceName: sota-core
          servicePort: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: sota-core-secret
type: Opaque
data:
  CORE_AWS_ACCESS_KEY: {{ .sota_core_aws_key | b64enc }}
  CORE_AWS_SECRET_KEY: {{ .sota_core_aws_secret | b64enc }}
  CORE_DB_PASSWORD: {{ .sota_core_db_password | b64enc }}
  JWT_SECRET: {{ .sota_core_jwt_secret | b64enc }}
---
apiVersion: v1
kind: Service
metadata:
  name: sota-core
spec:
  ports:
  - port: 80
    targetPort: 9001
  selector:
    app: sota-core
