---
apiVersion: v1
kind: ConfigMap
metadata:
  name: treehub-config
data:
  AUTH_PROTOCOL: none
  BIND_HOST: 0.0.0.0
  BIND_PORT: '9001'
  DB_MIGRATE: 'true'
  DB_URL: jdbc:mariadb://{{ .mysql_host }}:3306/treehub
  DB_USER: treehub
  DB_PASSWORD: treehub
  JAVA_OPTS: {{ .treehub_java_opts }}
  KAFKA_HOST: kafka:9092
  KAFKA_TOPIC_SUFFIX: {{ .kafka_topic_suffix }}
  MESSAGING_MODE: test
  SOTA_CORE_HOST: sota-core
  SOTA_CORE_PORT: '80'
  TREEHUB_HOSTNAME: http://treehub/api/v2/mydevice
  TREEHUB_LOCAL_STORE_PATH: "/treehub-objects"
  TREEHUB_STORAGE: local
  REPORT_METRICS: "false"
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: treehub
spec:
  selector:
    matchLabels:
      app: treehub
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: treehub
    spec:
      containers:
      - image: {{ .treehub_docker_image }}
        name: treehub
        envFrom:
        - configMapRef:
            name: treehub-config
        - secretRef:
            name: treehub-secret
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
        args:
        resources:
          requests:
            cpu: {{ .treehub_cpu }}
            memory: {{ .treehub_mem }}
        volumeMounts:
          - name: treehub-persistent-storage
            mountPath: /treehub-objects
        livenessProbe:
          initialDelaySeconds: 300
          periodSeconds: 30
          httpGet:
            port: 9001
            path: "/health"
      imagePullSecrets:
        - name: docker-registry-key
      volumes:
        - name: treehub-persistent-storage
          persistentVolumeClaim:
            claimName: treehub-pv-claim
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: treehub
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/proxy-body-size: 30m
spec:
  rules:
  - host: treehub.{{ .ingress_dns_name }}
    http:
      paths:
      - backend:
          serviceName: treehub
          servicePort: 80
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: treehub-pv-1
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/treehub-pv-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: treehub-pv-claim
  labels:
    app: treehub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: treehub-secret
type: Opaque
data:
  DB_PASSWORD: {{ .treehub_db_password | b64enc }}
  TREEHUB_AWS_ACCESS_KEY: {{ .treehub_aws_key | b64enc }}
  TREEHUB_AWS_SECRET_KEY: {{ .treehub_aws_secret | b64enc }}
---
apiVersion: v1
kind: Service
metadata:
  name: treehub
spec:
  ports:
  - port: 80
    targetPort: 9001
  selector:
    app: treehub
